### ISSUE TITLE
Exception while trying to add sensor

### ISSUE THREAD

**Issue by yaromins** [OpenAgInitiative/openag_brain_docker_rpi#11]
I'm trying to add dht22_sensor manually through adding record to firmware_module:
{
   "_id": "dht22_1",
   "_rev": "2-7b8aaa4b5fdbbb9d88b60de2f8215e20",
   "environment": "environment_1",
   "type": "dht22",
   "arguments": 4
}

Once I save I see following exception in logs:

[ERROR] [WallTime: 1472675181.990861] Failed to update Arduino
Traceback (most recent call last):
  File "/home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/sensor_persistence.py", line 114, in <module>
    create_persistence_objects(server)
  File "/home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/sensor_persistence.py", line 83, in create_persistence_objects
    module_db if not module_id.startswith('_')
  File "/home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/sensor_persistence.py", line 83, in <dictcomp>
    module_db if not module_id.startswith('_')
  File "/usr/local/lib/python2.7/dist-packages/voluptuous/schema_builder.py", line 192, in **call**
    return self._compiled([], data)
  File "/usr/local/lib/python2.7/dist-packages/voluptuous/schema_builder.py", line 486, in validate_dict
    return base_validate(path, iteritems(data), out)
  File "/usr/local/lib/python2.7/dist-packages/voluptuous/schema_builder.py", line 324, in validate_mapping
    raise er.MultipleInvalid(errors)
voluptuous.error.MultipleInvalid: expected a list for dictionary value @ data[u'arguments']

**Comment by yaromins** [comment]
Ok, fixed arguments to be an array, not just pin number.

But have new exceptions:

[INFO] [WallTime: 1472675974.304104] Filtering topic /sensors/dht22_1/air_humidity/raw to topic /sensors/dht22_1/air_humidity/filtered
[INFO] [WallTime: 1472675974.346329] Filtering topic /sensors/dht22_1/air_temperature/raw to topic /sensors/dht22_1/air_temperature/filtered
Traceback (most recent call last):
  File "/home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/topic_filter.py", line 64, in <module>
    filter_all_topics(module_db, module_type_db)
  File "/home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/topic_filter.py", line 53, in filter_all_topics
    topic_type = resolve_message_type(output_info["type"])
KeyError: 'type'
[WARN] [WallTime: 1472675974.609256] Traceback (most recent call last):
[WARN] [WallTime: 1472675974.614175] File "/usr/local/bin/openag", line 9, in <module>
[WARN] [WallTime: 1472675974.617937] load_entry_point('openag==0.1.3', 'console_scripts', 'openag')()
[WARN] [WallTime: 1472675974.621601] File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in **call**
[WARN] [WallTime: 1472675974.636611] return self.main(_args, *_kwargs)
[WARN] [WallTime: 1472675974.642091] File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
[WARN] [WallTime: 1472675974.647329] rv = self.invoke(ctx)
[WARN] [WallTime: 1472675974.652090] File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
[WARN] [WallTime: 1472675974.656827] return _process_result(sub_ctx.command.invoke(sub_ctx))
[WARN] [WallTime: 1472675974.661943] File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1060, in invoke
[WARN] [WallTime: 1472675974.667704] return _process_result(sub_ctx.command.invoke(sub_ctx))
[WARN] [WallTime: 1472675974.672987] File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
[WARN] [WallTime: 1472675974.677993] return ctx.invoke(self.callback, *_ctx.params)
[WARN] [WallTime: 1472675974.682915] File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
[WARN] [WallTime: 1472675974.688077] return callback(_args, **kwargs)
[WARN] [WallTime: 1472675974.693321] File "/usr/local/lib/python2.7/dist-packages/openag/cli/firmware/__init__.py", line 168, in run
[WARN] [WallTime: 1472675974.697917] for c in output_info["categories"]:
[WARN] [WallTime: 1472675974.702747] KeyError: 'categories'
[ERROR] [WallTime: 1472675974.738402] Failed to update Arduino
[topic_filter-6] process has died [pid 1458, exit code 1, cmd /home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/topic_filter.py __name:=topic_filter __log:=/home/pi/.ros/log/febe166a-6fba-11e6-8e54-0242ac120003/topic_filter-6.log].
log file: /home/pi/.ros/log/febe166a-6fba-11e6-8e54-0242ac120003/topic_filter-6_.log
Traceback (most recent call last):
  File "/home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/sensor_persistence.py", line 114, in <module>
    create_persistence_objects(server)
  File "/home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/sensor_persistence.py", line 100, in create_persistence_objects
    topic_type = resolve_message_type(output_info["type"])
KeyError: 'type'
[sensor_persistence_1-8] process has died [pid 1488, exit code 1, cmd /home/pi/catkin_ws/src/openag_brain/src/openag_brain/software_modules/sensor_persistence.py __name:=sensor_persistence_1 __log:=/home/pi/.ros/log/febe166a-6fba-11e6-8e54-0242ac120003/sensor_persistence_1-8.log].
log file: /home/pi/.ros/log/febe166a-6fba-11e6-8e54-0242ac120003/sensor_persistence_1-8_.log

Looks like I shall start with simple ds18b20  instead

**Comment by gordonbrander** [comment]
I think your problem is that `arguments` should be an array. 

```
...
"arguments": [4]
...
```

**Comment by gordonbrander** [comment]
Haha :D. You got there first. Can you paste the full content of your json fixture? I'll bet we can debug it.

**Comment by yaromins** [comment]
Seems that I fixed my sensor record  with

{
   "_id": "dht22_1",
   "_rev": "1-fc0ed34abbe5d6f1adaddf7903fbe15e",
   "type": "dht22",
   "environment": "environment_1",
   "arguments": [
       5
   ],
   "outputs": {
       "air_temperature": {
           "variable": "air_temperature"
       },
       "air_humidity": {
           "variable": "air_humidity"
       }
   }
}

Now I need to recall ;-) what exact sensor is connected to what pin on my arduino and see the actual readings from UI!
