### ISSUE TITLE
add .bashrc to docker image

### ISSUE THREAD

**Issue by yaromins** [OpenAgInitiative/openag_brain_docker_rpi#13]
During setup and debug process I often go to docker's bash to run `rostopic` command. 
To avoid manually run `source ./catkin_ws/devel/setup.bash` everytime I've created .bashrc

`# If not running interactively, don't do anything`
`[ -z "$PS1" ] && return`
`source ./catkin_ws/devel/setup.bash`

**Comment by LeonChambers** [comment]
I agree that this would be useful. This should be done in the Dockerfile of the openag_brain repo. If you submit a PR there with this change, I would be glad to merge it.
