### ISSUE TITLE
Error: Couldn't connect to Docker daemon

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain_docker_rpi#2]
After following the instructions in readme and doing `docker-compose up -d` I get the following:

```
Error: Couldn't connect to Docker daemon at http:docker://localunixsocket - is it running?
If it's a ta non-standard location, specify the URL with the DOCKER_HOST environment variable.
```

This was after starting a new terminal session.

**Comment by gordonbrander** [comment]
:/ restarting the Pi resolved the issue. Killing the session with `exit` didn't do the trick. Maybe because daemon is running in the background? We should update the docs.

**Comment by LeonChambers** [comment]
Lol I might know what this is. Did you do this setup process by plugging in an external monitor and clicking on the terminal application in the GUI? The actual solution is to log out and log back in, but I always either use a virtual console or ssh, so there isn't a difference.

For reference, the reason this happens is that installing docker adds the current user to a group called `docker` in the OS, and you have to force the OS to reload the list of groups that the current user belongs to.

**Comment by gordonbrander** [comment]
...yes. This is exactly what happened 😝. This is a bit unexpected. Worth noting in the instal instructions I think.

**Comment by LeonChambers** [comment]
Yea, definitely. I forgot normal people actually use GUIs

**Comment by gordonbrander** [comment]
Only this NOOB 👉 😇 👈
