### ISSUE TITLE
no personal_food_computer_v2.yml file

### ISSUE THREAD

**Issue by barwis** [OpenAgInitiative/openag_brain_docker_rpi#21]
I've been following the tutorial, but there's no personal_food_computer_v2.yml file, after installing docker.

**Comment by joakimbr** [comment]
I have the same problem..

**Comment by gordonbrander** [comment]
Can you paste a link to the tutorial you are following?

**Comment by joakimbr** [comment]
https://github.com/OpenAgInitiative/openag_brain_docker_rpi/blob/master/README.md

**Comment by gordonbrander** [comment]
Thanks! Looks like the README was slightly out-of-date. Updated now.

**Comment by joakimbr** [comment]
Great, thanks:)
