### ISSUE TITLE
Database data is deleted on reboot sometimes

### ISSUE THREAD

**Issue by sp4ghet** [OpenAgInitiative/openag_brain_docker_rpi#25]
When rebooting the Pi, the data on CouchDB was removed because it created a new container instead of using the previous container.

Adding a line to link the CouchDB `data/` directory to somewhere on the RPi file system would solve this problem.

Any ideas on a good place to do this?

**Comment by gordonbrander** [comment]
@Spaghet the couchdb container should be storing data in a volume https://docs.docker.com/engine/tutorials/dockervolumes/. Are you sure this is happening?

**Comment by sp4ghet** [comment]
I believe you need to explicitly specify them in the docker-compose.yml file for it to do the same thing as the `-v` flag. 
There is a fishy line in the Dockerfile https://github.com/dogi/rpi-couchdb/blob/master/Dockerfile#L56
which seems to mount the volume, but there is no such file on our Pi right now so I think it's not working as intended.

Currently the couchdb container stores things in its own file system, and it is not persistent if the container gets rm-ed. By mounting a volume, we can create new `db` containers and the data inside of them will remain persistent as long as the containers run compatible versions of couchdb.

I've tested #26 and it populates `/var/local/openag_db` with `.couch` files so it appears to mount correctly.

**Comment by sp4ghet** [comment]
https://docs.docker.com/engine/reference/builder/#volume

VOLUME in the dockerfile is used to link stuff from the base image to the new image, not to mount to the host OS. 

You could actually do something like `--volume-from old_container`  but this line in docker-compose  seems to be an easier approach to persistence
