### ISSUE TITLE
ERROR: for brain  Cannot start service brain

### ISSUE THREAD

**Issue by gordonbrander** [OpenAgInitiative/openag_brain_docker_rpi#3]
Got this error after running `docker-compose up -d`

```
pi@raspberrypi:~/openag_brain_docker_rpi $ docker-compose up -d
Pulling db (dogi/rpi-couchdb:latest)...
latest: Pulling from dogi/rpi-couchdb
c066fa7fbbaa: Pull complete
a3ed95caeb02: Pull complete
88f4a0792111: Pull complete
8a257955bed8: Pull complete
02ae6de0fa9a: Pull complete
20d773a3a0b7: Pull complete
8bfd02335ca9: Pull complete
1d4e897765fa: Pull complete
53dff47b29a9: Pull complete
5ee827101ef1: Pull complete
623f2ab5e738: Pull complete
77d88c73d744: Pull complete
7a6f320126b3: Pull complete
32ba8a9067b2: Pull complete
db6df28ea80a: Pull complete
Digest: sha256:b10941e6ed43f08b2aca68ca9116f4604543e2b10d6e8247be6429e5f57ee7b8
Status: Downloaded newer image for dogi/rpi-couchdb:latest
Pulling brain (openag/rpi_brain:latest)...
latest: Pulling from openag/rpi_brain
a3ed95caeb02: Pull complete
ba3827fc661c: Pull complete
2d0175befe79: Pull complete
a9a0626475df: Pull complete
67fcc541d69c: Pull complete
e7b1a08769d2: Pull complete
733b8e63266c: Pull complete
b6d3ac23cc9c: Pull complete
0e56c0bd729c: Pull complete
7767955eea19: Pull complete
3c25297ac38f: Pull complete
adb2fc87682d: Pull complete
Digest: sha256:30bf1bb04aa3ab6986554d0877caa08cb747c5ab9b37192008067e7d312065f7
Status: Downloaded newer image for openag/rpi_brain:latest
Creating openagbraindockerrpi_db_1
Creating openagbraindockerrpi_brain_1

ERROR: for brain  Cannot start service brain: linux runtime spec devices: error gathering device information while adding custom device "/dev/ttyACM0": lstat /dev/ttyACM0: no such file or directory
ERROR: Encountered errors while bringing up the project.
```

**Comment by LeonChambers** [comment]
Plugging an Arduino into the Pi should fix this. The handling of devices should probably be improved anyway. Something like mapping all of `/dev/bus/usb` into the container could avoid this problem and also allow the docker container to interact with other USB devices (e.g. a webcam or another Arduino). I made the assumption of a single Arduino on `/dev/ttyACM0` to get something working in the short term.

**Comment by gordonbrander** [comment]
😮 makes sense! I can just add a note about that in the instructions as well.

**Comment by R5T2** [comment]
Dear Gordon
I have started to build the FC and faced a problem.
Catched up your problem and faced the same error message as above after running `docker-compose up -d`. 
With plug in/out of arduino the error message 

> ...error gathering device information while adding custom device "/dev/ttyACM0": lstat /dev/ttyACM0: no such file or directory" 

stays.
USB port  `ls /dev/tty*` of arduino is named /DEV/ttyUSB0.
Are there any other action that I can perform to solve the issue?
Best regards from Switzerland
Marc
