### ISSUE TITLE
openagbraindockerrpi_brain_1 can not start

### ISSUE THREAD

**Issue by yaromins** [OpenAgInitiative/openag_brain_docker_rpi#8]
Checking logs I see constant error
usage: main [-h] [-D DATABASE] [-H HOSTNAME] [-f FIXTURE]
main: error: unrecognized arguments: -A http://brain:5000 --screen

**Comment by gordonbrander** [comment]
@serein7 what hardware are you using? Was the Arduino plugged in?

**Comment by yaromins** [comment]
@gordonbrander, RPI 3 with Arduino plugged, but no sensors attached.

**Comment by yaromins** [comment]
I see that -A param was added on Aug 10th with this commit https://github.com/OpenAgInitiative/openag_brain/commit/3886ce9abb0b1bc4e731cf380e041b71bbe25b67#diff-17bbe0107f52928f24a61a698bdc2f4f

Looks like image on https://hub.docker.com/r/openag/rpi_brain/  has older version of openag_brains, which did not support -A and --screen params. I had to manually change **docker-compose.yml** and remove those params from command line:

> command: ~/catkin_ws/devel/env.sh rosrun openag_brain main -D http://db:5984 -f default

this fixed this particular issue, but left me with next one:

> [Tue Aug 30 21:59:23 2016] Processing megaatmega2560 (platform: atmelavr, board: megaatmega2560, framework: arduino)
> BeforeUpload(["upload"], [".pioenvs/megaatmega2560/firmware.hex"])
> Looking for upload port/disk...
> 
> Warning! Please install `99-platformio-udev.rules` and check that your board's PID and VID are listed in the rules.
> https://raw.githubusercontent.com/platformio/platformio/develop/scripts/99-platformio-udev.rules
> 
> Auto-detected: /dev/ttyACM0
> scons: **\* [upload] could not open port /dev/ttyACM0: [Errno 13] Permission denied: '/dev/ttyACM0'

This is where I'm stuck at the moment. My pi user does has access to ACM0  (I did check that with miniterm). Any idea on next thing to try?

**Comment by yaromins** [comment]
One more detail. I got into docker container with 'docker exec -it openagbraindockerrpi_brain_1 bash
'
Indeed, the version of openag_brain seems to be outdated:

> pi@d74efdcac5c2:~/catkin_ws/src/openag_brain/scripts$ ls -l
> total 32
> -rwxr-xr-x 1 pi pi   60 Jun 14 17:50 flash_arduino
> -rwxr-xr-x 1 pi pi  494 Jun 14 17:50 generate_firmware
> -rwxr-xr-x 1 pi pi  588 Jun  9 19:48 init_db
> -rwxr-xr-x 1 pi pi  245 Jun 14 19:13 install_pio
> -rwxr-xr-x 1 pi pi  542 Jun  9 19:48 load_fixture
> -rwxr-xr-x 1 pi pi 3299 **Jun 14 21:10 main**
> drwxr-xr-x 2 pi pi 4096 Jun 14 21:04 software_modules
> -rwxr-xr-x 1 pi pi  490 Jun  9 19:48 update_launch

**Comment by LeonChambers** [comment]
I am certain that the image on DockerHub has been updated since the change to the command line arguments. Could you try deleting the docker image on your Pi and downloading it again?

**Comment by yaromins** [comment]
@LeonChambers, yes indeed my image was outdated. I'm new to docker stack and was confused by docker-compose output that containers are up-to-date assuming that it means that images are up to dates to docker's hub repository. Thank you for help.
